SUPPORTED_LANGUAGES = {"en", "fr"}
DEFAULT_LANGUAGE = "en"
SESSION_LANGUAGE_KEY = "site_language"


UI_TEXT = {
    "en": {
        "site_title": "Moses Zegbah Zimay | Finance, Digital Security & E-commerce Consultant",
        "site_description": "Premium consultant in Ivory Coast for accounting, OHADA compliance, digital security, WordPress, Shopify and business growth.",
        "nav_about": "About",
        "nav_about_overview": "Overview",
        "nav_services": "Services",
        "nav_why_choose": "Why Choose Me",
        "nav_pricing": "Pricing",
        "nav_projects": "Projects",
        "nav_blog": "Blog",
        "nav_courses": "Free Courses",
        "nav_diplomas": "Diplomas",
        "nav_contact": "Contact",
        "nav_whatsapp": "WhatsApp",
        "nav_tiktok": "TikTok",
        "nav_get_started": "Get Started",
        "nav_login": "Login",
        "nav_logout": "Logout",
        "nav_free_course": "Free Course",
        "theme_toggle": "Toggle color theme",
        "language_switcher": "Choose language",
        "footer_title": "Moses Zegbah Zimay",
        "footer_heading": "Finance clarity, digital trust and growth-ready execution.",
        "footer_intro": "Based in Ivory Coast and serving African businesses, NGOs and international teams with a rare mix of accounting discipline and digital consulting capability.",
        "footer_links": "Quick Links",
        "footer_services_title": "More Service",
        "footer_service_items": [
            "Accounting and Compliance",
            "Website Creation",
            "Shopify and E-commerce Setup",
            "Digital Security",
            "Business Advisory",
        ],
        "footer_contact_title": "Contact Info",
        "footer_contact_address": "Abidjan, Ivory Coast",
        "footer_contact_phone": "WhatsApp support available",
        "footer_contact_email": "Use the contact form for fast response",
        "footer_go_top": "Go To Top",
        "footer_coverage": "Coverage",
        "footer_coverage_items": [
            "Ivory Coast",
            "African SMEs",
            "NGOs and International Organizations",
            "E-commerce and Startup Advisory",
        ],
        "footer_copyright": "(c) 2026 Moses Zegbah Zimay. Premium consulting for accounting, compliance, digital security and e-commerce growth.",
        "success_message": "Your request has been received. Moses can now review it and follow up.",
        "error_message": "Please complete your name, email and project message before sending.",
        "contribution_success": "Contribution sent to admin successfully. It will be published after review.",
        "contribution_error": "Please provide your name, email and contribution content before submitting.",
        "blog_list_title": "Blog | Finance, Compliance & Digital Growth",
        "blog_list_description": "Insights on OHADA compliance, NGO finance, digital security, WordPress, Shopify and African e-commerce growth.",
        "blog_list_tag": "Insight Hub",
        "blog_list_heading": "Practical insights for finance, security and digital growth.",
        "blog_list_intro": "A focused blog for African SMEs, NGOs, founders and international teams that need reliable guidance on compliance, e-commerce and business resilience.",
        "community_tag": "Community Blog",
        "community_heading": "Share a suggestion or submit your own article.",
        "community_intro": "Visitors can propose article ideas or write full blog posts. Every submission is reviewed by the admin and published only after approval.",
        "community_name": "Your name",
        "community_email": "Your email",
        "community_type": "Contribution type",
        "community_type_article": "Blog article",
        "community_type_suggestion": "Suggestion",
        "community_category": "Category",
        "community_title": "Article title or suggestion subject",
        "community_excerpt": "Short summary",
        "community_content": "Write your suggestion or full article here.",
        "community_submit": "Send contribution",
        "community_note": "Email is required so the admin can contact contributors before or after review.",
        "read_article": "Read article",
        "back_to_blog": "Back to blog",
        "article_comments_title": "Comments",
        "article_comment_name": "Your name",
        "article_comment_email": "Your email",
        "article_comment_content": "Write your comment here.",
        "article_comment_submit": "Post comment",
        "article_comment_empty": "No comments yet. Be the first to comment.",
        "article_comment_success": "Your comment has been posted.",
        "article_comment_error": "Please fill in your name, email and comment.",
        "need_support": "Need support?",
        "detail_cta_heading": "Turn these insights into a cleaner, safer and more scalable operation.",
        "book_consultation": "Book a consultation",
        "courses_title": "Free Courses",
        "courses_heading": "Free courses by category, curated from ZAcademie.",
        "courses_intro": "Access courses after login. Pick a category and start learning.",
        "courses_login": "Log in to access courses",
        "courses_signup": "Create an account",
        "login_success": "Login successful. Welcome back.",
        "signup_success": "Account created successfully. Check your email to activate your account before login.",
        "activation_success": "Your email is confirmed. You can now sign in.",
        "courses_empty": "No videos yet. Add some in the admin panel.",
        "courses_category_finance": "Finance & Accounting",
        "courses_category_web": "Web Development",
        "courses_sub_shopify": "Shopify",
        "courses_sub_webflow": "Webflow",
        "courses_sub_wordpress": "WordPress",
        "courses_mark_done": "Mark as completed",
        "courses_mark_undo": "Mark as not completed",
        "courses_comments_title": "Questions & Comments",
        "courses_comment_placeholder": "Ask a question or add a comment.",
        "courses_comment_submit": "Send",
        "courses_comment_empty": "Be the first to comment on this video.",
        "courses_like": "Like",
        "courses_unlike": "Unlike",
        "projects_title": "Projects",
        "projects_heading": "Portfolio grouped by live projects and build projects.",
        "projects_intro": "Discover deployed apps and structured build projects from one page.",
        "projects_filter_all": "All projects",
        "projects_filter_live": "Live projects",
        "projects_filter_project": "Build projects",
        "projects_live_badge": "Projet live",
        "projects_build_badge": "Projet",
        "projects_open_live": "Open live",
        "projects_open_source": "Source",
        "projects_empty": "No project published yet for this category.",
        "projects_weather_heading": "SkyCast Pro - Meteo en direct",
        "projects_weather_intro": "Demo application integrated from your provided HTML/CSS/JS files. Add your OpenWeather API key in the JS file to fetch real data.",
        "diplomas_title": "Diplomas",
        "diplomas_heading": "Professional diplomas and certifications.",
        "diplomas_intro": "A dedicated page to review all published diplomas and certificates.",
        "diplomas_empty": "No diploma has been published yet.",
    },
    "fr": {
        "site_title": "Moses Zegbah Zimay | Consultant en finance, securite numerique et e-commerce",
        "site_description": "Consultant premium en Cote d'Ivoire pour la comptabilite, la conformite OHADA, la securite numerique, WordPress, Shopify et la croissance des entreprises.",
        "nav_about": "A propos",
        "nav_about_overview": "Vue d'ensemble",
        "nav_services": "Services",
        "nav_why_choose": "Pourquoi moi",
        "nav_pricing": "Tarifs",
        "nav_projects": "Projets",
        "nav_blog": "Blog",
        "nav_courses": "Cours Gratuits",
        "nav_diplomas": "Diplomes",
        "nav_contact": "Contact",
        "nav_whatsapp": "WhatsApp",
        "nav_tiktok": "TikTok",
        "nav_get_started": "Commencer",
        "nav_login": "Connexion",
        "nav_logout": "Deconnexion",
        "nav_free_course": "Cours Gratuit",
        "theme_toggle": "Changer le theme",
        "language_switcher": "Choisir la langue",
        "footer_title": "Moses Zegbah Zimay",
        "footer_heading": "Clarite financiere, confiance numerique et execution orientee croissance.",
        "footer_intro": "Base en Cote d'Ivoire, il accompagne les entreprises africaines, les ONG et les equipes internationales avec un profil rare melant rigueur comptable et conseil digital.",
        "footer_links": "Liens rapides",
        "footer_services_title": "Plus de services",
        "footer_service_items": [
            "Comptabilite et conformite",
            "Creation de sites web",
            "Mise en place Shopify et e-commerce",
            "Securite numerique",
            "Conseil business",
        ],
        "footer_contact_title": "Contact Info",
        "footer_contact_address": "Abidjan, Cote d'Ivoire",
        "footer_contact_phone": "Support WhatsApp disponible",
        "footer_contact_email": "Utilisez le formulaire de contact pour une reponse rapide",
        "footer_go_top": "Retour en haut",
        "footer_coverage": "Couverture",
        "footer_coverage_items": [
            "Cote d'Ivoire",
            "PME africaines",
            "ONG et organisations internationales",
            "Conseil e-commerce et startups",
        ],
        "footer_copyright": "(c) 2026 Moses Zegbah Zimay. Conseil premium en comptabilite, conformite, securite numerique et croissance e-commerce.",
        "success_message": "Votre demande a bien ete recue. Moses peut maintenant l'examiner et revenir vers vous.",
        "error_message": "Veuillez renseigner votre nom, votre e-mail et votre message de projet avant l'envoi.",
        "contribution_success": "Contribution envoyee a l'admin avec succes. Elle sera publiee apres validation.",
        "contribution_error": "Veuillez renseigner votre nom, votre e-mail et le contenu de votre contribution avant l'envoi.",
        "blog_list_title": "Blog | Finance, conformite et croissance digitale",
        "blog_list_description": "Analyses sur la conformite OHADA, la finance des ONG, la securite numerique, WordPress, Shopify et la croissance du e-commerce africain.",
        "blog_list_tag": "Centre de ressources",
        "blog_list_heading": "Des conseils pratiques pour la finance, la securite et la croissance digitale.",
        "blog_list_intro": "Un blog cible pour les PME africaines, les ONG, les fondateurs et les equipes internationales qui ont besoin de conseils fiables sur la conformite, le e-commerce et la resilience de l'entreprise.",
        "community_tag": "Blog participatif",
        "community_heading": "Partagez une suggestion ou proposez votre propre article.",
        "community_intro": "Les visiteurs peuvent proposer des idees d'articles ou rediger des billets complets. Chaque contribution est relue par l'admin et publiee uniquement apres approbation.",
        "community_name": "Votre nom",
        "community_email": "Votre e-mail",
        "community_type": "Type de contribution",
        "community_type_article": "Article de blog",
        "community_type_suggestion": "Suggestion",
        "community_category": "Categorie",
        "community_title": "Titre de l'article ou sujet de suggestion",
        "community_excerpt": "Resume court",
        "community_content": "Redigez ici votre suggestion ou votre article complet.",
        "community_submit": "Envoyer la contribution",
        "community_note": "L'e-mail est obligatoire pour que l'admin puisse contacter les contributeurs avant ou apres la relecture.",
        "read_article": "Lire l'article",
        "back_to_blog": "Retour au blog",
        "article_comments_title": "Commentaires",
        "article_comment_name": "Votre nom",
        "article_comment_email": "Votre e-mail",
        "article_comment_content": "Ecrivez votre commentaire ici.",
        "article_comment_submit": "Publier le commentaire",
        "article_comment_empty": "Aucun commentaire pour le moment. Soyez le premier.",
        "article_comment_success": "Votre commentaire a bien ete publie.",
        "article_comment_error": "Veuillez renseigner votre nom, votre e-mail et votre commentaire.",
        "need_support": "Besoin d'accompagnement ?",
        "detail_cta_heading": "Transformez ces analyses en une organisation plus propre, plus sure et plus evolutive.",
        "book_consultation": "Reserver une consultation",
        "courses_title": "Cours Gratuits",
        "courses_heading": "Des cours gratuits par categorie, issus de ZAcademie.",
        "courses_intro": "Acces aux cours apres connexion. Choisissez une categorie et commencez.",
        "courses_login": "Se connecter pour acceder aux cours",
        "courses_signup": "Creer un compte",
        "login_success": "Connexion reussie. Bon retour.",
        "signup_success": "Compte cree avec succes. Verifiez votre e-mail pour activer votre compte avant la connexion.",
        "activation_success": "Votre e-mail est confirme. Vous pouvez maintenant vous connecter.",
        "courses_empty": "Aucune video pour le moment. Ajoutez-en via l'admin.",
        "courses_category_finance": "Finance & Compta",
        "courses_category_web": "Developpement Web",
        "courses_sub_shopify": "Shopify",
        "courses_sub_webflow": "Webflow",
        "courses_sub_wordpress": "WordPress",
        "courses_mark_done": "Marquer comme termine",
        "courses_mark_undo": "Marquer non termine",
        "courses_comments_title": "Questions & Commentaires",
        "courses_comment_placeholder": "Posez votre question ou ajoutez un commentaire.",
        "courses_comment_submit": "Envoyer",
        "courses_comment_empty": "Soyez le premier a commenter cette video.",
        "courses_like": "J'aime",
        "courses_unlike": "Je n'aime plus",
        "projects_title": "Projets",
        "projects_heading": "Portfolio organise par projets live et projets.",
        "projects_intro": "Decouvrez les applications deja deployees et les projets en cours depuis une seule page.",
        "projects_filter_all": "Tous les projets",
        "projects_filter_live": "Projets live",
        "projects_filter_project": "Projets",
        "projects_live_badge": "Projet live",
        "projects_build_badge": "Projet",
        "projects_open_live": "Ouvrir en live",
        "projects_open_source": "Source",
        "projects_empty": "Aucun projet publie dans cette categorie.",
        "projects_weather_heading": "SkyCast Pro - Meteo en direct",
        "projects_weather_intro": "Application demo integree a partir de vos fichiers HTML/CSS/JS. Ajoutez votre cle API OpenWeather dans le JS pour recuperer les donnees reelles.",
        "diplomas_title": "Diplomes",
        "diplomas_heading": "Diplomes et certifications professionnels.",
        "diplomas_intro": "Une page dediee pour consulter tous les diplomes et certificats publies.",
        "diplomas_empty": "Aucun diplome publie pour le moment.",
    },
}


HOME_CONTENT = {
    "en": {
        "page_title": "Moses Zegbah Zimay | Premium Consultant for Finance, Security & E-commerce",
        "meta_description": "Premium consulting in Ivory Coast for accounting, compliance, digital security, WordPress, Shopify and business growth across Africa.",
        "hero_tag": "Secure Finance. Smart Growth.",
        "hero_heading": "Build a stronger business with compliance, digital security and premium execution.",
        "hero_intro": "Moses Zegbah Zimay helps African SMEs, NGOs, founders and international organizations strengthen accounting operations, secure digital assets, launch high-converting websites and structure scalable business growth.",
        "hero_primary_cta": "Book a consultation",
        "hero_secondary_cta": "Explore services",
        "hero_cv_cta": "Download CV",
        "hero_notes": ["Based in Ivory Coast", "French / English", "OHADA, SYCEBNL, IFRS"],
        "status_cards": [
            {
                "label": "Core positioning",
                "title": "Hybrid consultant for finance and digital performance",
                "text": "Rare expertise spanning accounting discipline, web delivery, cybersecurity awareness and e-commerce advisory.",
            },
            {
                "label": "High-trust sectors",
                "title": "NGOs, organizations, SMEs and ambitious founders",
                "text": "Designed for clients who need credibility, reporting rigor and secure digital execution.",
            },
            {
                "label": "Tools",
                "title": "SAGE, QuickBooks, Xero, WordPress and Shopify",
                "text": "Operational support that connects finance systems, digital assets and business visibility.",
            },
        ],
        "security_badge_tag": "Security Badge",
        "security_badge_heading": "Protected growth mindset",
        "security_badge_text": "Finance control, website resilience and business clarity working together to reduce risk and increase trust.",
        "credibility_tag": "Certification",
        "credibility_heading": "Last certification or diploma",
        "credibility_link_cta": "View all diplomas",
        "portfolio_tag": "Portfolio",
        "portfolio_heading": "Existing digital presence available online.",
        "portfolio_intro": "Moses already has a live online portfolio. This site now complements that presence with a stronger premium consulting narrative, tighter positioning and better business conversion structure.",
        "portfolio_primary_cta": "View diplomas",
        "portfolio_secondary_cta": "Open CV PDF",
        "portfolio_points": [
            "Better positioning for NGOs, SMEs, international organizations and founders",
            "Clearer offer packaging for websites, maintenance, compliance and advisory",
            "Stronger proof stack through credential and downloadable CV access",
        ],
        "about_tag": "About",
        "about_heading": "Credibility built at the intersection of finance discipline and digital execution.",
        "about_intro": "Moses Zegbah Zimay is a consultant based in Ivory Coast with a profile that is especially valuable for organizations operating in complex, high-trust environments. His background includes accounting support, compliance awareness, digital security thinking and website delivery for business growth.",
        "about_points": [
            "Accounting Assistant experience at the Inter-African Coffee Organization",
            "Exposure to multi-currency accounting environments including XOF and EUR",
            "Practical understanding of bank reconciliation, budgeting, audit support and financial reporting",
            "Working knowledge of OHADA, SYCEBNL and IFRS-oriented environments",
        ],
        "authority_tag": "Authority Snapshot",
        "authority_heading": "Trusted for operations that must be both clean and secure.",
        "authority_text": "Whether the challenge is a donor-facing finance process, a business website that needs more credibility, or a digital operation that needs stronger protection, the focus remains the same: create systems that are reliable, professional and growth-ready.",
        "authority_badges": ["Finance and Compliance", "Digital Security", "WordPress and Shopify", "Business Advisory"],
        "services_tag": "Services",
        "services_heading": "Premium services designed for trust, resilience and measurable business progress.",
        "services_intro": "Every offer is structured around a simple promise: protect the business, strengthen the numbers and create better growth conditions.",
        "why_choose_tag": "Why Choose Me",
        "why_choose_heading": "A rare profile for organizations that need both rigor and agility.",
        "call_tag": "Call Us 24/7",
        "call_heading": "Need support on an urgent finance, compliance or digital issue?",
        "call_text": "For active projects and advisory missions, responsive support helps reduce downtime, clarify decisions quickly and protect business continuity.",
        "call_whatsapp_cta": "Open WhatsApp",
        "call_callback_cta": "Request a callback",
        "call_badges": ["Fast response mindset", "Security-aware advisory"],
        "pricing_tag": "Pricing",
        "pricing_heading": "Clear starting points for premium engagements.",
        "pricing_intro": "Pricing is intentionally positioned for serious businesses that want trust, quality execution and expert support rather than generic low-cost delivery.",
        "cta_tag": "Security First",
        "cta_heading": "Protect the business while building the next stage of growth.",
        "cta_text": "The strongest brands are not only visible. They are financially disciplined, operationally credible and digitally secure.",
        "cta_button": "Start your project",
        "testimonials_tag": "Testimonials",
        "testimonials_heading": "Professional clients value clarity, reliability and high-trust execution.",
        "blog_tag": "Blog",
        "blog_heading": "SEO-ready insights on compliance, NGO finance, digital security and African e-commerce.",
        "blog_intro": "The blog is designed to strengthen authority, capture search traffic and demonstrate deep practical understanding of the client sectors Moses serves.",
        "community_tag": "Community Blog",
        "community_heading": "Share a suggestion or submit your own article.",
        "community_intro": "Visitors can propose article ideas or write full blog posts. Every submission is reviewed by the admin and published only after approval.",
        "community_name": "Your name",
        "community_email": "Your email",
        "community_type": "Contribution type",
        "community_type_article": "Blog article",
        "community_type_suggestion": "Suggestion",
        "community_category": "Category",
        "community_title": "Article title or suggestion subject",
        "community_excerpt": "Short summary",
        "community_content": "Write your suggestion or full article here.",
        "community_submit": "Send contribution",
        "community_note": "Email is required so the admin can contact contributors before or after review.",
        "contact_tag": "Contact",
        "contact_heading": "Ready to secure your operations and accelerate business growth?",
        "contact_intro": "Whether you need a premium website, stronger accounting control, a safer digital environment or business structuring support, this is the right place to start the conversation.",
        "contact_items": [
            {"label": "Location", "value": "Ivory Coast, serving clients across Africa and international networks"},
            {"label": "Support style", "value": "Consulting, retainers, project delivery and advisory sessions"},
            {"label": "Primary CTA", "value": "Use the form or open WhatsApp for a fast project discussion"},
        ],
        "contact_whatsapp_cta": "WhatsApp CTA",
        "contact_tiktok_cta": "Open TikTok",
        "contact_blog_cta": "Read the blog",
        "project_brief_tag": "Project Brief",
        "form_name": "Your name or organization",
        "form_email": "Business email",
        "form_service": "Service needed: website, accounting, security, consulting",
        "form_message": "Tell us about your business, your challenge and your timeline.",
        "form_submit": "Send project request",
    },
    "fr": {
        "page_title": "Moses Zegbah Zimay | Consultant premium en finance, securite et e-commerce",
        "meta_description": "Conseil premium en Cote d'Ivoire pour la comptabilite, la conformite, la securite numerique, WordPress, Shopify et la croissance en Afrique.",
        "hero_tag": "Finance securisee. Croissance intelligente.",
        "hero_heading": "Construisez une entreprise plus solide avec la conformite, la securite numerique et une execution premium.",
        "hero_intro": "Moses Zegbah Zimay aide les PME africaines, les ONG, les fondateurs et les organisations internationales a renforcer leurs operations comptables, securiser leurs actifs numeriques, lancer des sites web performants et structurer une croissance durable.",
        "hero_primary_cta": "Reserver une consultation",
        "hero_secondary_cta": "Decouvrir les services",
        "hero_cv_cta": "Telecharger le CV",
        "hero_notes": ["Base en Cote d'Ivoire", "Francais / Anglais", "OHADA, SYCEBNL, IFRS"],
        "status_cards": [
            {
                "label": "Positionnement central",
                "title": "Consultant hybride en finance et performance digitale",
                "text": "Une expertise rare qui relie rigueur comptable, creation web, sensibilite cybersecurite et conseil e-commerce.",
            },
            {
                "label": "Secteurs a forte confiance",
                "title": "ONG, organisations, PME et fondateurs ambitieux",
                "text": "Concu pour les clients qui ont besoin de credibilite, de rigueur de reporting et d'une execution digitale securisee.",
            },
            {
                "label": "Outils",
                "title": "SAGE, QuickBooks, Xero, WordPress et Shopify",
                "text": "Un accompagnement operationnel qui relie systemes financiers, actifs digitaux et visibilite business.",
            },
        ],
        "security_badge_tag": "Badge securite",
        "security_badge_heading": "Une croissance protegee",
        "security_badge_text": "Controle financier, resilience du site web et clarte business travaillent ensemble pour reduire le risque et renforcer la confiance.",
        "credibility_tag": "Certification",
        "credibility_heading": "Derniere certification ou diplome",
        "credibility_link_cta": "Voir tous les diplomes",
        "portfolio_tag": "Portfolio",
        "portfolio_heading": "Une presence digitale deja disponible en ligne.",
        "portfolio_intro": "Moses possede deja un portfolio en ligne. Ce site renforce cette presence avec un positionnement premium plus clair, une proposition de valeur plus convaincante et un parcours mieux structure pour convertir les visiteurs en clients.",
        "portfolio_primary_cta": "Voir diplomes",
        "portfolio_secondary_cta": "Ouvrir le CV PDF",
        "portfolio_points": [
            "Un meilleur positionnement pour les ONG, les PME, les organisations internationales et les fondateurs",
            "Des offres plus claires pour les sites web, la maintenance, la conformite et le conseil",
            "Des preuves plus solides via les certificats et le CV telechargeable",
        ],
        "about_tag": "A propos",
        "about_heading": "Une credibilite construite au croisement de la rigueur financiere et de l'execution digitale.",
        "about_intro": "Moses Zegbah Zimay est un consultant base en Cote d'Ivoire avec un profil particulierement utile aux organisations qui evoluent dans des environnements complexes et sensibles a la confiance. Son parcours couvre l'appui comptable, la conformite, la securite numerique et la creation de sites au service de la croissance.",
        "about_points": [
            "Experience d'assistant comptable a l'Organisation Interafricaine du Cafe",
            "Exposition a des environnements comptables multi-devises incluant XOF et EUR",
            "Bonne maitrise du rapprochement bancaire, du budget, de l'appui audit et du reporting financier",
            "Connaissance pratique des environnements OHADA, SYCEBNL et IFRS",
        ],
        "authority_tag": "Resume d'autorite",
        "authority_heading": "Une expertise de confiance pour des operations qui doivent etre propres et securisees.",
        "authority_text": "Qu'il s'agisse d'un processus financier lie a des bailleurs, d'un site web qui doit gagner en credibilite ou d'une operation digitale qui a besoin de plus de protection, l'objectif reste le meme : creer des systemes fiables, professionnels et prets pour la croissance.",
        "authority_badges": ["Finance et conformite", "Securite numerique", "WordPress et Shopify", "Conseil business"],
        "services_tag": "Services",
        "services_heading": "Des services premium pensés pour la confiance, la resilience et une progression business mesurable.",
        "services_intro": "Chaque offre repose sur une promesse simple : proteger l'entreprise, renforcer les chiffres et creer de meilleures conditions de croissance.",
        "why_choose_tag": "Pourquoi moi",
        "why_choose_heading": "Un profil rare pour les organisations qui ont besoin a la fois de rigueur et d'agilite.",
        "call_tag": "Appelez-nous 24/7",
        "call_heading": "Besoin d'aide sur un sujet urgent en finance, conformite ou digital ?",
        "call_text": "Pour les projets actifs et les missions de conseil, une assistance reactive permet de reduire les interruptions, d'eclaircir rapidement les decisions et de proteger la continuite de l'activite.",
        "call_whatsapp_cta": "Ouvrir WhatsApp",
        "call_callback_cta": "Demander un rappel",
        "call_badges": ["Reactivite", "Conseil sensible a la securite"],
        "pricing_tag": "Tarifs",
        "pricing_heading": "Des points d'entree clairs pour des engagements premium.",
        "pricing_intro": "Les tarifs sont volontairement positionnes pour les entreprises serieuses qui recherchent confiance, qualite d'execution et accompagnement expert plutot qu'une prestation low-cost generique.",
        "cta_tag": "Securite d'abord",
        "cta_heading": "Protegez l'entreprise tout en construisant sa prochaine phase de croissance.",
        "cta_text": "Les marques les plus solides ne sont pas seulement visibles. Elles sont aussi rigoureuses financierement, credibles operationnellement et securisees numeriquement.",
        "cta_button": "Demarrer votre projet",
        "testimonials_tag": "Temoignages",
        "testimonials_heading": "Les clients professionnels valorisent la clarte, la fiabilite et une execution a forte confiance.",
        "blog_tag": "Blog",
        "blog_heading": "Des analyses optimisées SEO sur la conformite, la finance des ONG, la securite numerique et le e-commerce africain.",
        "blog_intro": "Le blog est concu pour renforcer l'autorite, capter du trafic de recherche et montrer une comprehension pratique des secteurs clients servis par Moses.",
        "community_tag": "Blog participatif",
        "community_heading": "Partagez une suggestion ou proposez votre propre article.",
        "community_intro": "Les visiteurs peuvent proposer des idees d'articles ou rediger des billets complets. Chaque contribution est relue par l'admin et publiee uniquement apres approbation.",
        "community_name": "Votre nom",
        "community_email": "Votre e-mail",
        "community_type": "Type de contribution",
        "community_type_article": "Article de blog",
        "community_type_suggestion": "Suggestion",
        "community_category": "Categorie",
        "community_title": "Titre de l'article ou sujet de suggestion",
        "community_excerpt": "Resume court",
        "community_content": "Redigez ici votre suggestion ou votre article complet.",
        "community_submit": "Envoyer la contribution",
        "community_note": "L'e-mail est obligatoire pour que l'admin puisse contacter les contributeurs avant ou apres la relecture.",
        "contact_tag": "Contact",
        "contact_heading": "Pret a securiser vos operations et accelerer votre croissance ?",
        "contact_intro": "Que vous ayez besoin d'un site premium, d'un meilleur controle comptable, d'un environnement digital plus sur ou d'un accompagnement en structuration business, c'est le bon endroit pour lancer la conversation.",
        "contact_items": [
            {"label": "Localisation", "value": "Cote d'Ivoire, avec des clients en Afrique et a l'international"},
            {"label": "Style d'accompagnement", "value": "Conseil, retainer, livraison de projet et sessions d'accompagnement"},
            {"label": "CTA principal", "value": "Utilisez le formulaire ou ouvrez WhatsApp pour discuter rapidement de votre projet"},
        ],
        "contact_whatsapp_cta": "CTA WhatsApp",
        "contact_tiktok_cta": "Ouvrir TikTok",
        "contact_blog_cta": "Lire le blog",
        "project_brief_tag": "Brief projet",
        "form_name": "Votre nom ou organisation",
        "form_email": "E-mail professionnel",
        "form_service": "Service souhaite : site web, comptabilite, securite, conseil",
        "form_message": "Parlez-nous de votre entreprise, de votre besoin et de votre delai.",
        "form_submit": "Envoyer la demande",
    },
}


def get_language(request):
    language = request.session.get(SESSION_LANGUAGE_KEY, DEFAULT_LANGUAGE)
    if language not in SUPPORTED_LANGUAGES:
        language = DEFAULT_LANGUAGE
    return language


def get_ui_text(language):
    return UI_TEXT.get(language, UI_TEXT[DEFAULT_LANGUAGE])


def get_home_content(language):
    return HOME_CONTENT.get(language, HOME_CONTENT[DEFAULT_LANGUAGE])
