# Generated by Codex on 2026-03-27

from django.db import migrations


def remove_seeded_video(apps, schema_editor):
    CourseVideo = apps.get_model("app", "CourseVideo")
    CourseVideo.objects.filter(title="Creation d'un site web avec Shopify").delete()


def restore_seeded_video(apps, schema_editor):
    CourseCategory = apps.get_model("app", "CourseCategory")
    CourseSubcategory = apps.get_model("app", "CourseSubcategory")
    CourseVideo = apps.get_model("app", "CourseVideo")

    web = CourseCategory.objects.filter(name="Developpement Web").first()
    shopify = CourseSubcategory.objects.filter(name="Shopify").first()
    if not web:
        return
    CourseVideo.objects.get_or_create(
        title="Creation d'un site web avec Shopify",
        category=web,
        subcategory=shopify,
        defaults={
            "youtube_url": "https://youtu.be/KOU8a-2HWr4?si=fBp77HPkhTgWWdxL",
            "description": "Tutoriel complet de creation d'un site web avec Shopify.",
            "order": 2,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_add_shopify_video"),
    ]

    operations = [
        migrations.RunPython(remove_seeded_video, restore_seeded_video),
    ]
