# Generated by Codex on 2026-03-27

from django.db import migrations
from django.utils.text import slugify


def seed_courses(apps, schema_editor):
    CourseCategory = apps.get_model("app", "CourseCategory")
    CourseSubcategory = apps.get_model("app", "CourseSubcategory")
    CourseVideo = apps.get_model("app", "CourseVideo")

    finance, _ = CourseCategory.objects.get_or_create(
        name="Finance & Compta",
        defaults={"order": 1, "slug": slugify("Finance & Compta")},
    )
    web, _ = CourseCategory.objects.get_or_create(
        name="Developpement Web",
        defaults={"order": 2, "slug": slugify("Developpement Web")},
    )

    shopify, _ = CourseSubcategory.objects.get_or_create(
        category=web, name="Shopify", defaults={"order": 1, "slug": slugify("Shopify")}
    )
    CourseSubcategory.objects.get_or_create(
        category=web, name="Webflow", defaults={"order": 2, "slug": slugify("Webflow")}
    )
    CourseSubcategory.objects.get_or_create(
        category=web, name="WordPress", defaults={"order": 3, "slug": slugify("WordPress")}
    )

    CourseVideo.objects.get_or_create(
        title="Creation de boutique ecommerce Shopify",
        category=web,
        subcategory=shopify,
        defaults={
            "youtube_url": "https://www.youtube.com/watch?v=3v2hf2maqvQ",
            "description": "Introduction a la creation de boutique Shopify.",
            "order": 1,
        },
    )


def unseed_courses(apps, schema_editor):
    CourseSubcategory = apps.get_model("app", "CourseSubcategory")
    CourseCategory = apps.get_model("app", "CourseCategory")
    CourseVideo = apps.get_model("app", "CourseVideo")

    CourseVideo.objects.filter(title="Creation de boutique ecommerce Shopify").delete()
    CourseSubcategory.objects.filter(name__in=["Shopify", "Webflow", "WordPress"]).delete()
    CourseCategory.objects.filter(name__in=["Finance & Compta", "Developpement Web"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_coursecategory_coursesubcategory_coursevideo"),
    ]

    operations = [
        migrations.RunPython(seed_courses, unseed_courses),
    ]
