# Generated by Django 6.0.3 on 2026-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_seeded_shopify_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='youtube_url',
            field=models.TextField(),
        ),
    ]
