POSTS_BY_LANGUAGE = {
    "en": [
        {
            "id": 1,
            "slug": "ohada-reforms-2026-african-smes",
            "category": "OHADA & Compliance",
            "title": "OHADA reforms in 2026: what African SMEs must update now",
            "excerpt": "A practical breakdown of the accounting and governance updates that matter for growing companies operating under OHADA standards.",
            "read_time": "6 min read",
            "date": "March 2026",
            "content": [
                "OHADA compliance is no longer just a filing requirement. It is becoming a competitive advantage for African companies that need investor confidence, audit readiness, and stronger operational control.",
                "For SMEs, the priority is to review the chart of accounts, tighten supporting documentation, and align reporting routines with management decision-making. Too many businesses wait until year-end before fixing structural weaknesses.",
                "A stronger approach is to combine monthly bookkeeping discipline, bank reconciliation, and management reporting so leadership can make decisions with reliable numbers. This is especially important when the company works with donors, suppliers, or foreign partners.",
                "When compliance is treated as a growth system instead of an administrative burden, finance becomes a tool for credibility, cash control, and scale.",
            ],
        },
        {
            "id": 2,
            "slug": "financial-management-for-ngos-donor-controls",
            "category": "NGO Finance",
            "title": "Financial management for NGOs: the controls donors expect",
            "excerpt": "From multi-currency controls to audit trails, here is what international organizations and NGOs need for resilient financial operations.",
            "read_time": "7 min read",
            "date": "March 2026",
            "content": [
                "NGOs and international organizations operate under intense pressure for transparency, grant compliance, and reporting accuracy. Weak controls create risk not only for finance teams, but for the credibility of the whole program.",
                "Strong NGO financial management starts with clean documentation, clear approval workflows, segregated responsibilities, and reliable month-end reporting. Multi-currency environments also require disciplined exchange-rate treatment and reconciliation practices.",
                "Donors increasingly expect finance teams to produce evidence quickly. That means bookkeeping, budget tracking, and supporting schedules should be review-ready at all times, not only during audits.",
                "Organizations that build finance systems around visibility and discipline are better positioned to protect funding, satisfy audits, and support long-term impact.",
            ],
        },
        {
            "id": 3,
            "slug": "cyber-hygiene-for-african-businesses",
            "category": "Digital Security",
            "title": "Cyber hygiene for African businesses: simple actions with high impact",
            "excerpt": "A business-focused security checklist for SMEs, consultants, and e-commerce operators that want to reduce digital risk fast.",
            "read_time": "5 min read",
            "date": "March 2026",
            "content": [
                "Many businesses do not need complicated cybersecurity stacks to reduce risk. They need disciplined basics executed consistently across devices, websites, payment workflows, and internal access.",
                "The highest-impact actions are enabling multi-factor authentication, securing website updates, limiting admin access, backing up critical data, and training teams to identify phishing attempts.",
                "For WordPress and Shopify environments, security must be built into maintenance. That includes plugin hygiene, strong credential management, uptime monitoring, and recovery plans.",
                "Digital trust is now part of brand value. A secure business protects revenue, reputation, and customer confidence.",
            ],
        },
        {
            "id": 4,
            "slug": "building-ecommerce-between-africa-and-global-markets",
            "category": "E-commerce",
            "title": "Building an e-commerce business between Africa and international markets",
            "excerpt": "The financial, operational, and technical foundations needed to launch and scale an online business across borders.",
            "read_time": "8 min read",
            "date": "March 2026",
            "content": [
                "Cross-border e-commerce gives African founders access to wider markets, but it also increases the need for operational structure. Payment flows, taxes, customer experience, and financial reporting must work together.",
                "Too many stores focus only on design and products. High-performing e-commerce businesses align brand positioning, conversion-focused pages, logistics, accounting visibility, and risk controls from the start.",
                "A strong launch stack includes a conversion-ready website, clear product messaging, trustworthy checkout flows, bookkeeping discipline, and performance dashboards that show what is actually driving growth.",
                "When digital execution and financial structure are aligned, e-commerce becomes more scalable, more bankable, and easier to manage.",
            ],
        },
    ],
    "fr": [
        {
            "id": 1,
            "slug": "reformes-ohada-2026-pme-africaines",
            "category": "OHADA et conformite",
            "title": "Reformes OHADA en 2026 : ce que les PME africaines doivent mettre a jour maintenant",
            "excerpt": "Une lecture pratique des evolutions comptables et de gouvernance qui comptent pour les entreprises en croissance sous les normes OHADA.",
            "read_time": "Lecture 6 min",
            "date": "Mars 2026",
            "content": [
                "La conformite OHADA n'est plus seulement une obligation declarative. Elle devient un avantage concurrentiel pour les entreprises africaines qui recherchent la confiance des investisseurs, la preparation a l'audit et un meilleur controle operationnel.",
                "Pour les PME, la priorite est de revoir le plan comptable, de renforcer les pieces justificatives et d'aligner les routines de reporting sur la prise de decision. Trop d'entreprises attendent la fin d'exercice avant de corriger les faiblesses structurelles.",
                "Une approche plus solide consiste a combiner une discipline comptable mensuelle, le rapprochement bancaire et le reporting de gestion afin que les dirigeants puissent decider a partir de chiffres fiables. C'est encore plus important lorsque l'entreprise travaille avec des bailleurs, des fournisseurs ou des partenaires etrangers.",
                "Quand la conformite est pensee comme un systeme de croissance plutot qu'une charge administrative, la finance devient un outil de credibilite, de maitrise de tresorerie et de passage a l'echelle.",
            ],
        },
        {
            "id": 2,
            "slug": "gestion-financiere-ong-controles-bailleurs",
            "category": "Finance des ONG",
            "title": "Gestion financiere des ONG : les controles attendus par les bailleurs",
            "excerpt": "Des controles multi-devises aux pistes d'audit, voici ce dont les organisations internationales et les ONG ont besoin pour des operations financieres resilientes.",
            "read_time": "Lecture 7 min",
            "date": "Mars 2026",
            "content": [
                "Les ONG et les organisations internationales evoluent sous une forte pression de transparence, de conformite aux subventions et de precision du reporting. Des controles faibles exposent non seulement l'equipe finance, mais aussi la credibilite de tout le programme.",
                "Une bonne gestion financiere des ONG commence par une documentation propre, des circuits d'approbation clairs, une separation des responsabilites et un reporting de fin de mois fiable. Les environnements multi-devises exigent aussi une gestion rigoureuse des taux de change et des rapprochements.",
                "Les bailleurs attendent de plus en plus des equipes finance qu'elles puissent produire rapidement des preuves. Cela signifie que la comptabilite, le suivi budgetaire et les annexes justificatives doivent etre prets a etre revus a tout moment, pas seulement pendant les audits.",
                "Les organisations qui construisent leur systeme financier autour de la visibilite et de la discipline sont mieux positionnees pour proteger les financements, satisfaire les audits et soutenir l'impact sur le long terme.",
            ],
        },
        {
            "id": 3,
            "slug": "hygiene-cyber-entreprises-africaines",
            "category": "Securite numerique",
            "title": "Hygiene cyber pour les entreprises africaines : des actions simples a fort impact",
            "excerpt": "Une checklist securite orientee business pour les PME, consultants et acteurs e-commerce qui veulent reduire rapidement le risque numerique.",
            "read_time": "Lecture 5 min",
            "date": "Mars 2026",
            "content": [
                "Beaucoup d'entreprises n'ont pas besoin de piles cybersecurite complexes pour reduire le risque. Elles ont surtout besoin de fondamentaux bien executes de facon constante sur les appareils, les sites web, les flux de paiement et les acces internes.",
                "Les actions a plus fort impact sont l'activation de l'authentification multi-facteurs, la securisation des mises a jour du site, la limitation des acces administrateur, la sauvegarde des donnees critiques et la formation des equipes au phishing.",
                "Dans les environnements WordPress et Shopify, la securite doit etre integree a la maintenance. Cela inclut l'hygiene des plugins, la gestion solide des identifiants, la surveillance de disponibilite et les plans de reprise.",
                "La confiance numerique fait maintenant partie de la valeur d'une marque. Une entreprise securisee protege son chiffre d'affaires, sa reputation et la confiance de ses clients.",
            ],
        },
        {
            "id": 4,
            "slug": "construire-ecommerce-afrique-marches-internationaux",
            "category": "E-commerce",
            "title": "Construire un business e-commerce entre l'Afrique et les marches internationaux",
            "excerpt": "Les bases financieres, operationnelles et techniques necessaires pour lancer et faire croitre un commerce en ligne a travers les frontieres.",
            "read_time": "Lecture 8 min",
            "date": "Mars 2026",
            "content": [
                "Le e-commerce transfrontalier ouvre aux fondateurs africains l'acces a des marches plus larges, mais il renforce aussi le besoin de structure operationnelle. Les paiements, les taxes, l'experience client et le reporting financier doivent fonctionner ensemble.",
                "Trop de boutiques se concentrent uniquement sur le design et les produits. Les activites e-commerce les plus performantes alignent des le depart le positionnement de marque, les pages orientees conversion, la logistique, la visibilite comptable et les controles de risque.",
                "Une pile de lancement solide comprend un site pret a convertir, un message produit clair, un tunnel de paiement fiable, une discipline comptable et des tableaux de bord de performance qui montrent ce qui genere vraiment la croissance.",
                "Quand l'execution digitale et la structure financiere sont alignees, le e-commerce devient plus scalable, plus bancable et plus facile a piloter.",
            ],
        },
    ],
}


def get_posts(language):
    return POSTS_BY_LANGUAGE.get(language, POSTS_BY_LANGUAGE["en"])
