# Generated by Codex on 2026-03-27

from django.db import migrations


def add_shopify_video(apps, schema_editor):
    CourseCategory = apps.get_model("blog", "CourseCategory")
    CourseSubcategory = apps.get_model("blog", "CourseSubcategory")
    CourseVideo = apps.get_model("blog", "CourseVideo")

    web = CourseCategory.objects.filter(name="Developpement Web").first()
    shopify = CourseSubcategory.objects.filter(name="Shopify").first()
    if not web:
        return

    CourseVideo.objects.get_or_create(
        title="Creation d'un site web avec Shopify",
        category=web,
        subcategory=shopify,
        defaults={
            "youtube_url": "https://youtu.be/KOU8a-2HWr4?si=fBp77HPkhTgWWdxL",
            "description": "Tutoriel complet de creation d'un site web avec Shopify.",
            "order": 2,
        },
    )


def remove_shopify_video(apps, schema_editor):
    CourseVideo = apps.get_model("blog", "CourseVideo")
    CourseVideo.objects.filter(title="Creation d'un site web avec Shopify").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_coursecommentlike"),
    ]

    operations = [
        migrations.RunPython(add_shopify_video, remove_shopify_video),
    ]
