# Generated by Django 6.0.3 on 2026-03-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_coursevideo_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('issuer', models.CharField(max_length=220)),
                ('date_label', models.CharField(blank=True, max_length=60)),
                ('summary', models.TextField(blank=True)),
                ('image_source', models.CharField(help_text='URL (https://...) or static path (example: blog/assets/img/certificate.jpg).', max_length=255)),
                ('certificate_source', models.CharField(blank=True, help_text='URL or static path to the certificate/document.', max_length=255)),
                ('cta_label', models.CharField(default='Open certificate', max_length=80)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
