# Generated by Django 6.0.3 on 2026-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('live', 'Projet live'), ('project', 'Projet')], default='project', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover_source', models.CharField(blank=True, help_text='URL (https://...) or static path (example: blog/assets/img/project-cover.jpg).', max_length=255)),
                ('live_url', models.CharField(blank=True, help_text='External URL (https://...) or internal path (example: /projects/weather-live/).', max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
